package crml.language.xtext;

import java.io.ByteArrayInputStream;
import java.io.IOException;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.junit.jupiter.api.Test;

import com.google.inject.Injector;

import crml.model.language.Definition;
import crml.model.language.DefinitionType;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Parses CRML model text using the XText grammar (CrmlXtext.xtext).
 *
 * CrmlXtextStandaloneSetup is generated by the generateXtextLanguage Gradle
 * task from CrmlXtext.xtext.  Definition and DefinitionType come from the
 * shared :model subproject (crml.model.language.*).
 * Run `./gradlew :language-xtext:generateXtextLanguage` first if generated
 * classes are missing.
 */
public class CrmlXtextParserTest {

    // One injector shared across all tests in this class
    private static final Injector INJECTOR =
            new CrmlXtextStandaloneSetup().createInjectorAndDoEMFRegistration();

    // ── Happy-path tests ──────────────────────────────────────────────────────

    @Test
    void parsesModelDefinition() throws IOException {
        Resource resource = parse("model Foo is { };");

        assertNoErrors(resource);
        Definition def = rootAs(resource, Definition.class);
        assertEquals(DefinitionType.MODEL, def.getKind());
        assertEquals("Foo", def.getName());
    }

    @Test
    void parsesPackageDefinition() throws IOException {
        Resource resource = parse("package MyLib is { };");

        assertNoErrors(resource);
        Definition def = rootAs(resource, Definition.class);
        assertEquals(DefinitionType.PACKAGE, def.getKind());
        assertEquals("MyLib", def.getName());
    }

    @Test
    void parsesLibraryDefinition() throws IOException {
        Resource resource = parse("library Stdlib is { };");

        assertNoErrors(resource);
        Definition def = rootAs(resource, Definition.class);
        assertEquals(DefinitionType.LIBRARY, def.getKind());
        assertEquals("Stdlib", def.getName());
    }

    // ── Error-case tests ──────────────────────────────────────────────────────

    @Test
    void rejectsUnknownDefinitionKeyword() throws IOException {
        Resource resource = parse("component Foo is { };");
        assertFalse(resource.getErrors().isEmpty(),
                "Expected parse errors for unknown definition keyword");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private Resource parse(String text) throws IOException {
        XtextResourceSet rs = INJECTOR.getInstance(XtextResourceSet.class);
        Resource resource = rs.createResource(URI.createURI("dummy:/test.crmlx"));
        resource.load(new ByteArrayInputStream(text.getBytes()), null);
        return resource;
    }

    private static void assertNoErrors(Resource resource) {
        assertTrue(resource.getErrors().isEmpty(),
                "Unexpected parse errors: " + resource.getErrors());
    }

    @SuppressWarnings("unchecked")
    private static <T> T rootAs(Resource resource, Class<T> type) {
        assertFalse(resource.getContents().isEmpty(), "Resource has no content");
        Object root = resource.getContents().get(0);
        assertInstanceOf(type, root);
        return (T) root;
    }
}
